Bands=[
    {"ID": "001", 
    "Band Name" : "Abichova", 
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "2005 ",
    "Founded In": "Lucerne, CH",
    "Country": "Switzerland",
    "N° of Albums": "3",
    "N° of Singles": "4",
    "Newest Album": "Weltenwanderer",
    "Year": "2018",
    "N°1 Most Popular Album": "Wegweiser",
    "2° Most Popular Album": "Weltenwanderer",
    "3° Most Popular Album": "Versteckte Pfade",
    "Top Song": "Handgeschrieben",
    "2° Top Song": "Vom grünen grund",
    "3° Top Song": "Weltenwanderer",
    "4° Top Song": "Lichtfänger",
    "5° Top Song": "Felsenfrass",
    "Spotify Listeners": "418",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "002", 
    "Band Name" : "Adorned Brood",
    "Genre" : "Folk Metal", 
    "Year Formed": "1993 ",
    "Founded In": "Grevenbroich, DE",
    "Country": "Germany",
    "N° of Albums": "8",
    "N° of Singles": "1",
    "Newest Album": "Kuningaz",
    "Year": "2012",
    "N°1 Most Popular Album": "Kuningaz",
    "2° Most Popular Album": "Hammerefeste",
    "3° Most Popular Album": "Noor",
    "Top Song": "Munin",
    "2° Top Song": "Kuningaz",
    "3° Top Song": "Hugin",
    "4° Top Song": "Victory or Valhall",
    "5° Top Song": "Men!",
    "Spotify Listeners": "5107",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "003", 
    "Band Name" : "Alestorm",
    "Genre" : "Folk/Power Metal", 
    "Year Formed": "2007 ",
    "Founded In": "Perth, UK",
    "Country": "United Kingdom",
    "N° of Albums": "7",
    "N° of Singles": "15",
    "Newest Album": "Seventh Rum of a Seventh Rum",
    "Year": "2022",
    "N°1 Most Popular Album": "Seventh Rum of a Seventh Rum",
    "2° Most Popular Album": "Curse of the Crystal Coconut",
    "3° Most Popular Album": "No Grave but the Sea",
    "Top Song": "Drink",
    "2° Top Song": "Fucked with an Anchor",
    "3° Top Song": "Keelhauled",
    "4° Top Song": "The Sunking Norwegian",
    "5° Top Song": "Shipwrecked",
    "Spotify Listeners": "844394",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "South America & Australia"},

    {"ID": "004", 
    "Band Name" : "Altars of Grief",
    "Genre" : "Black/Funeral Doom Metal", 
    "Year Formed": "2013 ",
    "Founded In": "Regina, CA",
    "Country": "Canada",
    "N° of Albums": "3",
    "N° of Singles": "1",
    "Newest Album": "This Shameful Burden",
    "Year": "2018",
    "N°1 Most Popular Album": "Iris",
    "2° Most Popular Album": "Of Ash and Dying Light...",
    "3° Most Popular Album": "This Shameful Burden",
    "Top Song": "Isolation",
    "2° Top Song": "Desolation",
    "3° Top Song": "Child of Light",
    "4° Top Song": "Iris",
    "5° Top Song": "Room of Angel",
    "Spotify Listeners": "873",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "Canada"},

    {"ID": "005", 
    "Band Name" : "Alter Bridge",
    "Genre" : "Hard Rock/ Heavy Metal/Alternative Metal", 
    "Year Formed": "2004 ",
    "Founded In": "Orlando, US",
    "Country": "United States",
    "N° of Albums": "7",
    "N° of Singles": "23",
    "Newest Album": "Walk the Sky 2.0",
    "Year": "2020",
    "N°1 Most Popular Album": "One Day Remains",
    "2° Most Popular Album": "Blackbird",
    "3° Most Popular Album": "Fortress",
    "Top Song": "Metalingus",
    "2° Top Song": "Watch Over You",
    "3° Top Song": "Silver Tongue",
    "4° Top Song": "Oper Your Eyes",
    "5° Top Song": "In Loving Memory",
    "Spotify Listeners": "2053434",
    "In tour?": "Yes",
    "When?": "2022/2023",
    "Where?": "US/EU"},

    {"ID": "006", 
    "Band Name" : "Amon Amarth",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "1992 ",
    "Founded In": "Stockholm, SE",
    "Country": "Sweden",
    "N° of Albums": "12",
    "N° of Singles": "11",
    "Newest Album": "The Great Heathen Army",
    "Year": "2022",
    "N°1 Most Popular Album": "Twilight Of The Thunder God",
    "2° Most Popular Album": "Surtur Rising",
    "3° Most Popular Album": "Jomsviking",
    "Top Song": "Twilight Of The Thunder God",
    "2° Top Song": "Guardians Of Asgaard",
    "3° Top Song": "Put Your Back Ito The Oar",
    "4° Top Song": "The Pursuit Of VIkings",
    "5° Top Song": "Raise Your Horns",
    "Spotify Listeners": "1464224",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU/US"},

    {"ID": "007", 
    "Band Name" : "Amon Amarth",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "1992 ",
    "Founded In": "Stockholm, SE",
    "Country": "Sweden",
    "N° of Albums": "12",
    "N° of Singles": "11",
    "Newest Album": "The Great Heathen Army",
    "Year": "2022",
    "N°1 Most Popular Album": "Twilight Of The Thunder God",
    "2° Most Popular Album": "Surtur Rising",
    "3° Most Popular Album": "Jomsviking",
    "Top Song": "Twilight Of The Thunder God",
    "2° Top Song": "Guardians Of Asgaard",
    "3° Top Song": "Put Your Back Ito The Oar",
    "4° Top Song": "The Pursuit Of VIkings",
    "5° Top Song": "Raise Your Horns",
    "Spotify Listeners": "1464224",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU/US"},

    {"ID": "008", 
    "Band Name" : "Ancient Bards",
    "Genre" : "Symphonic Power Metal", 
    "Year Formed": "2006 ",
    "Founded In": "Rimini, IT",
    "Country": "Italy",
    "N° of Albums": "4",
    "N° of Singles": "5",
    "Newest Album": "Origine - The Black Crystal Sword Saga Part 2",
    "Year": "2019",
    "N°1 Most Popular Album": "Origine - The Black Crystal Sword Saga Part 2",
    "2° Most Popular Album": "Soulless Child",
    "3° Most Popular Album": "The Alliance of the Kings - The Black Crystal Sword Saga Pt.1",
    "Top Song": "Trough My Veins",
    "2° Top Song": "Across This Life",
    "3° Top Song": "Light",
    "4° Top Song": "Impious Dystopia",
    "5° Top Song": "In My Arms",
    "Spotify Listeners": "51375",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "009", 
    "Band Name" : "Asenblut",
    "Genre" : "Black/Thrash/Pagan Metal", 
    "Year Formed": "2006 ",
    "Founded In": "Göttingen, DE",
    "Country": "Germany",
    "N° of Albums": "4",
    "N° of Singles": "0",
    "Newest Album": "Die wilde Jagd",
    "Year": "2020",
    "N°1 Most Popular Album": "Die wilde Jagd",
    "2° Most Popular Album": "Berserker",
    "3° Most Popular Album": "Legenden",
    "Top Song": "Berserkerzorn",
    "2° Top Song": "Seite an Seite",
    "3° Top Song": "Asenblut",
    "4° Top Song": "Die wilde Jagd",
    "5° Top Song": "Gor or Man",
    "Spotify Listeners": "15401",
    "In tour?": "Yes",
    "When?": "2022/20223",
    "Where?": "EU"},

    {"ID": "010", 
    "Band Name" : "Battlelore",
    "Genre" : "Epic Symphonic Metal", 
    "Year Formed": "1999 ",
    "Founded In": "Lappeenranta, FI",
    "Country": "Finland",
    "N° of Albums": "7",
    "N° of Singles": "0",
    "Newest Album": "The Return of the Shadow",
    "Year": "2022",
    "N°1 Most Popular Album": "The Return of the Shadow",
    "2° Most Popular Album": "Swors Song",
    "3° Most Popular Album": "The Last Alliance",
    "Top Song": "Sons of Riddermark",
    "2° Top Song": "Chambers of FIre",
    "3° Top Song": "Third Immortal",
    "4° Top Song": "The War of Wrath",
    "5° Top Song": "Firekeeper",
    "Spotify Listeners": "26061",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "011", 
    "Band Name" : "Bifröst",
    "Genre" : "Pagan/Folk Metal", 
    "Year Formed": "2005 ",
    "Founded In": "Salzburg, AT",
    "Country": "Austria",
    "N° of Albums": "4",
    "N° of Singles": "0",
    "Newest Album": "Mana Ewah",
    "Year": "2016",
    "N°1 Most Popular Album": "Tor in eine neue Welt",
    "2° Most Popular Album": "Heidenmetal",
    "3° Most Popular Album": "Mana Ewah",
    "Top Song": "Wer mit dir steht",
    "2° Top Song": "Blutrote Nacht",
    "3° Top Song": "Runde um Runde",
    "4° Top Song": "Am Pfahle",
    "5° Top Song": "Rangarök",
    "Spotify Listeners": "3015",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "012", 
    "Band Name" : "Black Messiah",
    "Genre" : "Symphonic Black/Folk/Viking Metal", 
    "Year Formed": "1992",
    "Founded In": "Gelsenkirchen, DE",
    "Country": "Germany",
    "N° of Albums": "7",
    "N° of Singles": "0",
    "Newest Album": "Walls of Vanaheim",
    "Year": "2017",
    "N°1 Most Popular Album": "Walls of Vanaheim",
    "2° Most Popular Album": "Of Myths and Legends",
    "3° Most Popular Album": "First War of the World",
    "Top Song": "Sauflied",
    "2° Top Song": "Soeldnerschwein",
    "3° Top Song": "Loki Tanz",
    "4° Top Song": "Die Bürde Des Njörd",
    "5° Top Song": "Satisfation and Revenge",
    "Spotify Listeners": "35610",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "013", 
    "Band Name" : "Blind Guardian",
    "Genre" : "Power Metal", 
    "Year Formed": "1984",
    "Founded In": "Krefeld, DE",
    "Country": "Germany",
    "N° of Albums": "18",
    "N° of Singles": "0",
    "Newest Album": "The God Machine",
    "Year": "2022",
    "N°1 Most Popular Album": "Nightfall in Middle Earth",
    "2° Most Popular Album": "Somewhere Far Behind",
    "3° Most Popular Album": "Memories of a Time to Come",
    "Top Song": "The Bards Song",
    "2° Top Song": "Valhalla",
    "3° Top Song": "Mirror Mirror",
    "4° Top Song": "Twilight of the Gods",
    "5° Top Song": "Nightfall",
    "Spotify Listeners": "825186",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "014", 
    "Band Name" : "Bloodbound",
    "Genre" : "Heavy/Power Metal", 
    "Year Formed": "2004",
    "Founded In": "Bollnäs, SE",
    "Country": "Sweden",
    "N° of Albums": "9",
    "N° of Singles": "6",
    "Newest Album": "Creatures of the Dark Realm",
    "Year": "2021",
    "N°1 Most Popular Album": "War of Dragons",
    "2° Most Popular Album": "Unholy Cross",
    "3° Most Popular Album": "Rise of the Dragon Empire",
    "Top Song": "Rise of the Dragon Empire",
    "2° Top Song": "Tears of a Dragonheart",
    "3° Top Song": "Moria",
    "4° Top Song": "Nosferatu",
    "5° Top Song": "Buttle in the Sky",
    "Spotify Listeners": "335970",
    "In tour?": "Yes",
    "When?": "2022/2023",
    "Where?": "EU"},

    {"ID": "015", 
    "Band Name" : "Brothers of Metal",
    "Genre" : "Heavy/Power Metal", 
    "Year Formed": "2012",
    "Founded In": "Malung, SE",
    "Country": "Sweden",
    "N° of Albums": "3",
    "N° of Singles": "8",
    "Newest Album": "Emblas Saga",
    "Year": "2020",
    "N°1 Most Popular Album": "Prophecy of Ragnarök",
    "2° Most Popular Album": "Emblas Saga",
    "3° Most Popular Album": "Fire Blood and Steel / Blood on Fire",
    "Top Song": "Yggdrasil",
    "2° Top Song": "Prophecy of Ragnarök",
    "3° Top Song": "Fire Blood and Steel",
    "4° Top Song": "Ride of the Valkyries",
    "5° Top Song": "Son of Odin",
    "Spotify Listeners": "750717",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "016", 
    "Band Name" : "Brymir",
    "Genre" : "Symphonic/Melodic Death/Pagan Metal", 
    "Year Formed": "2006",
    "Founded In": "Helsinki, FI",
    "Country": "Finland",
    "N° of Albums": "4",
    "N° of Singles": "4",
    "Newest Album": "Voices in the Sky",
    "Year": "2022",
    "N°1 Most Popular Album": "Breath Fire to the Sun",
    "2° Most Popular Album": "Wings of Fire",
    "3° Most Popular Album": "Voices in the Sky",
    "Top Song": "Ragnarök",
    "2° Top Song": "Wings of Fire",
    "3° Top Song": "Herald of Aegir",
    "4° Top Song": "Forged in War",
    "5° Top Song": "Fly with Me",
    "Spotify Listeners": "55083",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "017", 
    "Band Name" : "Burzum",
    "Genre" : "Black Metal, Ambient", 
    "Year Formed": "1991",
    "Founded In": "Bergen, NO ",
    "Country": "Norway",
    "N° of Albums": "13",
    "N° of Singles": "3",
    "Newest Album": "Thulêan Mysteries",
    "Year": "2020",
    "N°1 Most Popular Album": "The Ways of Yore",
    "2° Most Popular Album": "The Ways of Yore",
    "3° Most Popular Album": "Burzum",
    "Top Song": "Dunkelheit",
    "2° Top Song": "Jesus Tod",
    "3° Top Song": "War",
    "4° Top Song": "Erbicket Die Tochter Des Firmaments",
    "5° Top Song": "Lost Wisdom",
    "Spotify Listeners": "185876",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "018", 
    "Band Name" : "Cernunnos",
    "Genre" : "Folk Metal", 
    "Year Formed": "2012",
    "Founded In": "Buenos Aires, AR",
    "Country": "Argentina",
    "N° of Albums": "2",
    "N° of Singles": "1",
    "Newest Album": "Capricornvs",
    "Year": "2021",
    "N°1 Most Popular Album": "",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Mabon",
    "2° Top Song": "Dragonborn",
    "3° Top Song": "The Svmmoner",
    "4° Top Song": "Capricornvs",
    "5° Top Song": "Scarborough Fair",
    "Spotify Listeners": "490",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "019", 
    "Band Name" : "Civil War",
    "Genre" : "Heavy/Power Metal", 
    "Year Formed": "2012",
    "Founded In": "Falun, SE",
    "Country": "Sweden",
    "N° of Albums": "6",
    "N° of Singles": "5",
    "Newest Album": "Invaders",
    "Year": "2022",
    "N°1 Most Popular Album": "The Killer Angels",
    "2° Most Popular Album": "Rome Is Falling",
    "3° Most Popular Album": "The Last Full Measure",
    "Top Song": "Rome Is Falling",
    "2° Top Song": "I Will Rule the Universe",
    "3° Top Song": "Bay of Pigs",
    "4° Top Song": "Oblivion",
    "5° Top Song": "Tombstone",
    "Spotify Listeners": "109879",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "020", 
    "Band Name" : "Craving",
    "Genre" : "Melodic Death/Black Metal with Celtic folk influences", 
    "Year Formed": "2006",
    "Founded In": "Oldenburg, DE",
    "Country": "Germany",
    "N° of Albums": "3",
    "N° of Singles": "2",
    "Newest Album": "By the Storm",
    "Year": "2016",
    "N°1 Most Popular Album": "By the Storm",
    "2° Most Popular Album": "At Dawn",
    "3° Most Popular Album": "Craving",
    "Top Song": "By Storm",
    "2° Top Song": "Only Teardrops",
    "3° Top Song": "Penelopes Prayer",
    "4° Top Song": "Wielder of Storms",
    "5° Top Song": "Wenn Der Wind Sich Dreht",
    "Spotify Listeners": "5411",
    "In tour?": "NO",
    "When?": "",
    "Where?": ""},

    {"ID": "021",
    "Band Name" : "Cruachan",
    "Genre" : "Celtic Folk/Black Metal", 
    "Year Formed": "1993",
    "Founded In": "Dublin, IE",
    "Country": "Ireland",
    "N° of Albums": "8",
    "N° of Singles": "3",
    "Newest Album": "Nine Years of Blood",
    "Year": "2018",
    "N°1 Most Popular Album": "Folk-Lore",
    "2° Most Popular Album": "Blood for the Blood God",
    "3° Most Popular Album": "The Morrigans Call",
    "Top Song": "Blood for the Blood God",
    "2° Top Song": "Ride On",
    "3° Top Song": "The Morrigans Call",
    "4° Top Song": "The Marching Song of Fiach Mac Hugh",
    "5° Top Song": "Some Say The Devil Is Dead",
    "Spotify Listeners": "42462",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "022", 
    "Band Name" : "Dalriada",
    "Genre" : "Folk Metal", 
    "Year Formed": "2003",
    "Founded In": "Sopron, HU",
    "Country": "Hungary",
    "N° of Albums": "12",
    "N° of Singles": "3",
    "Newest Album": "Öszelö",
    "Year": "2021",
    "N°1 Most Popular Album": "Nyárutó",
    "2° Most Popular Album": "Napisten Hava",
    "3° Most Popular Album": "Ígéret",
    "Top Song": "Nyárutó",
    "2° Top Song": "Hajdútánc",
    "3° Top Song": "Napisten Hava",
    "4° Top Song": "Amit ad az ég",
    "5° Top Song": "Megöltek egy legényt",
    "Spotify Listeners": "22138",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "023", 
    "Band Name" : "Danheim",
    "Genre" : "Ambient Folk", 
    "Year Formed": "2016",
    "Founded In": "Copenhagen, DK",
    "Country": "Denmark",
    "N° of Albums": "8",
    "N° of Singles": "36",
    "Newest Album": "Domadagr",
    "Year": "2021",
    "N°1 Most Popular Album": "Skapanir",
    "2° Most Popular Album": "Domadgr",
    "3° Most Popular Album": "Hringrás",
    "Top Song": "Berserkir",
    "2° Top Song": "Ivars Revenge",
    "3° Top Song": "Hefna",
    "4° Top Song": "Temple of Odin",
    "5° Top Song": "Runar",
    "Spotify Listeners": "488463",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "024", 
    "Band Name" : "Dark Tranquillity",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "1991",
    "Founded In": "Gothenburg, SE",
    "Country": "Sweden",
    "N° of Albums": "19",
    "N° of Singles": "16",
    "Newest Album": "Moment",
    "Year": "2020",
    "N°1 Most Popular Album": "Fiction",
    "2° Most Popular Album": "Atoma",
    "3° Most Popular Album": "Moment",
    "Top Song": "Atoma",
    "2° Top Song": "Miserys Crown",
    "3° Top Song": "Forward Momentum",
    "4° Top Song": "Lethe",
    "5° Top Song": "Panthom Days",
    "Spotify Listeners": "274088",
    "In tour?": "Yes",
    "When?": "2023",
    "Where?": "EU"},

    {"ID": "025", 
    "Band Name" : "Dead Crown",
    "Genre" : "Black Metal/Ambient", 
    "Year Formed": "2009",
    "Founded In": "Bayonne, FR",
    "Country": "France",
    "N° of Albums": "5",
    "N° of Singles": "0",
    "Newest Album": "Tales from the Frozen Lands Part I & II",
    "Year": "2021",
    "N°1 Most Popular Album": "Tales From The Frozen Lands Part I",
    "2° Most Popular Album": "Nature Is My Temple",
    "3° Most Popular Album": "Frozen Blood",
    "Top Song": "The Raven King",
    "2° Top Song": "Madre Del Trueno",
    "3° Top Song": "Dawn Of The End",
    "4° Top Song": "Nebula",
    "5° Top Song": "Frozen Blood",
    "Spotify Listeners": "216",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "026", 
    "Band Name" : "The Declawed",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "2020",
    "Founded In": "Kotka, FI",
    "Country": "Finland",
    "N° of Albums": "1",
    "N° of Singles": "0",
    "Newest Album": "Howls",
    "Year": "2020",
    "N°1 Most Popular Album": "Howls",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Howls",
    "2° Top Song": "Cynical Resign",
    "3° Top Song": "The Great Mist Of a Lie",
    "4° Top Song": "Circle Of Entropy",
    "5° Top Song": "",
    "Spotify Listeners": "6",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "027", 
    "Band Name" : "Def Leppard",
    "Genre" : "Heavy Metal", 
    "Year Formed": "1977",
    "Founded In": "Sheffield, UK",
    "Country": "United Kingdom",
    "N° of Albums": "20",
    "N° of Singles": "30",
    "Newest Album": "Diamond Star Halos",
    "Year": "2022",
    "N°1 Most Popular Album": "Hysteria",
    "2° Most Popular Album": "Pyromania",
    "3° Most Popular Album": "Retroactive",
    "Top Song": "Pour Some Sugar On Me",
    "2° Top Song": "Hysteria",
    "3° Top Song": "Photograph",
    "4° Top Song": "Rock Of Ages",
    "5° Top Song": "Love Bites",
    "Spotify Listeners": "6735092",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "US"},

    {"ID": "028", 
    "Band Name" : "DevilDriver",
    "Genre" : "Groove/Melodic Deat", 
    "Year Formed": "2003",
    "Founded In": "Santa Barbara, US",
    "Country": "United States",
    "N° of Albums": "9",
    "N° of Singles": "15",
    "Newest Album": "	Dealing with Demons, Volume I",
    "Year": "2020",
    "N°1 Most Popular Album": "Dealing With Demons I",
    "2° Most Popular Album": "Outlaws Til The End, Vol. 1",
    "3° Most Popular Album": "Trust No One",
    "Top Song": "Sail",
    "2° Top Song": "Clouds Over Califronia",
    "3° Top Song": "I Could Care Less",
    "4° Top Song": "Endf Of The Line",
    "5° Top Song": "Hold Back The Day",
    "Spotify Listeners": "441239",
    "In tour?": "Yes",
    "When?": "2023",
    "Where?": "EU"},

    {"ID": "029", 
    "Band Name" : "Diamond Head",
    "Genre" : "Heavy Metal/Hard Rock", 
    "Year Formed": "1976",
    "Founded In": "Stourbridge, UK",
    "Country": "United Kingdom",
    "N° of Albums": "9",
    "N° of Singles": "5",
    "Newest Album": "Lightning to the Nations",
    "Year": "2020",
    "N°1 Most Popular Album": "Diamond Head",
    "2° Most Popular Album": "The Coffin Train",
    "3° Most Popular Album": "Lightning To The Nations",
    "Top Song": "Am I Evil?",
    "2° Top Song": "Am I Evil",
    "3° Top Song": "Its Electric",
    "4° Top Song": "Dead Reckoning",
    "5° Top Song": "No Remorse",
    "Spotify Listeners": "244064",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "030", 
    "Band Name" : "Die Apokalyptischen Reiter",
    "Genre" : "Death/Folk Metal", 
    "Year Formed": "1995",
    "Founded In": "Apolda, DE",
    "Country": "Germany",
    "N° of Albums": "12",
    "N° of Singles": "5",
    "Newest Album": "Wilde Kinder",
    "Year": "2022",
    "N°1 Most Popular Album": "The Divine Horsemen",
    "2° Most Popular Album": "Der Rote Reiter",
    "3° Most Popular Album": "Wilde Kinder",
    "Top Song": "Ghostriders in the Sky",
    "2° Top Song": "Auf und nieder",
    "3° Top Song": "Der Adler",
    "4° Top Song": "Seemann",
    "5° Top Song": "Freiheit Gleichheit Brüderlichkeit",
    "Spotify Listeners": "358383",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "031", 
    "Band Name" : "Dio",
    "Genre" : "Heavy Metal", 
    "Year Formed": "1982",
    "Founded In": "New York, US",
    "Country": "United States",
    "N° of Albums": "10",
    "N° of Singles": "22",
    "Newest Album": "Master of the Moon",
    "Year": "2004",
    "N°1 Most Popular Album": "Wings Of Steel",
    "2° Most Popular Album": "Business In Hell",
    "3° Most Popular Album": "The Hands of Fate",
    "Top Song": "Rainbow In The Dark",
    "2° Top Song": "Holy Diver",
    "3° Top Song": "The Last In Line",
    "4° Top Song": "Dont Talk To Strangers",
    "5° Top Song": "We Rock",
    "Spotify Listeners": "2980659",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "032", 
    "Band Name" : "DragonForce",
    "Genre" : "Power Metal", 
    "Year Formed": "1999",
    "Founded In": "London, UK",
    "Country": "United Kingdom",
    "N° of Albums": "8",
    "N° of Singles": "0",
    "Newest Album": "Extreme Power Metal",
    "Year": "2019",
    "N°1 Most Popular Album": "Killer Elite",
    "2° Most Popular Album": "Re-Powered WIthin",
    "3° Most Popular Album": "Inhuman Rampage",
    "Top Song": "Through The Fire And Flames",
    "2° Top Song": "Fury Of The Storm",
    "3° Top Song": "Cry Thunder",
    "4° Top Song": "Soldiers Of The Wastelands",
    "5° Top Song": "Heroes Of Our Time",
    "Spotify Listeners": "1822311",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "033", 
    "Band Name" : "Dragonsifre",
    "Genre" : "Melodic Heavy Metal", 
    "Year Formed": "2005",
    "Founded In": "Riedstadt, DE",
    "Country": "Germany",
    "N° of Albums": "3",
    "N° of Singles": "1",
    "Newest Album": "Speed Demon / Metal X",
    "Year": "2015",
    "N°1 Most Popular Album": "Masters of the Underground",
    "2° Most Popular Album": "Speed Demon",
    "3° Most Popular Album": "Metal Service",
    "Top Song": "Speed Demon",
    "2° Top Song": "To Hell and Back",
    "3° Top Song": "Drgansfire Rockxxx",
    "4° Top Song": "Wings of Death",
    "5° Top Song": "Morris Tunes",
    "Spotify Listeners": "385",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "034", 
    "Band Name" : "Dreamtale",
    "Genre" : "Melodic Power Metal", 
    "Year Formed": "Tampere, FI",
    "Founded In": "1999",
    "Country": "Finland",
    "N° of Albums": "8",
    "N° of Singles": "5",
    "Newest Album": "Everlasting Flame",
    "Year": "2022",
    "N°1 Most Popular Album": "Seventhian... Memories of Time",
    "2° Most Popular Album": "World Changed Forever",
    "3° Most Popular Album": "Everlasting Flame",
    "Top Song": "Angel Of Light",
    "2° Top Song": "Greenback Hunter",
    "3° Top Song": "Tides of War",
    "4° Top Song": "Dreality",
    "5° Top Song": "Take What the Heavens Cerate",
    "Spotify Listeners": "51234",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "035", 
    "Band Name" : "Duskmourn",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "2012",
    "Founded In": "Jersey, US",
    "Country": "United States",
    "N° of Albums": "3",
    "N° of Singles": "0",
    "Newest Album": "Fallen Kings and Rusted Crowns",
    "Year": "2021",
    "N°1 Most Popular Album": "Fallen Kings and Rusted Crowns",
    "2° Most Popular Album": "Of Shadow and Flame",
    "3° Most Popular Album": "Legends",
    "Top Song": "Fallen Kings And Rusted Crowns",
    "2° Top Song": "Forged by Fire and Stone",
    "3° Top Song": "Deathless",
    "4° Top Song": "The Sleeping Tide",
    "5° Top Song": "Blood of the Forest",
    "Spotify Listeners": "7967",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "036", 
    "Band Name" : "Eluveitie",
    "Genre" : "Folk/Melodic Death Metal, Folk", 
    "Year Formed": "2002",
    "Founded In": "Zürich, CH ",
    "Country": "Switzerland",
    "N° of Albums": "8",
    "N° of Singles": "12",
    "Newest Album": "Ategnatos",
    "Year": "2019",
    "N°1 Most Popular Album": "Origins",
    "2° Most Popular Album": "Evocation II - Pantheon",
    "3° Most Popular Album": "Slania",
    "Top Song": "The Call of the Mountains",
    "2° Top Song": "Inis Mona",
    "3° Top Song": "Ambriramus",
    "4° Top Song": "A Rose for Epona",
    "5° Top Song": "Thousandfold",
    "Spotify Listeners": "656177",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "037", 
    "Band Name" : "Elvenking",
    "Genre" : "Melodic Power/Folk Metal", 
    "Year Formed": "1997",
    "Founded In": "Sacile, IT",
    "Country": "Italy",
    "N° of Albums": "10",
    "N° of Singles": "8",
    "Newest Album": "Reader of the Runes - Divination",
    "Year": "2019",
    "N°1 Most Popular Album": "The Winter Wake",
    "2° Most Popular Album": "Reader of the Runes - Divination",
    "3° Most Popular Album": "Heathenreel",
    "Top Song": "Elvenlegions",
    "2° Top Song": "Silverseal",
    "3° Top Song": "Pagan Revolution",
    "4° Top Song": "The Divided Heart",
    "5° Top Song": "Black Roses for the Wicked One",
    "Spotify Listeners": "239604",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "038", 
    "Band Name" : "Ensiferum",
    "Genre" : "Epic Folk Metal", 
    "Year Formed": "1995",
    "Founded In": "Helsinki, FI",
    "Country": "Finland",
    "N° of Albums": "8",
    "N° of Singles": "7",
    "Newest Album": "Thalassic",
    "Year": "2020",
    "N°1 Most Popular Album": "Two Paths",
    "2° Most Popular Album": "Suomi Warmetal",
    "3° Most Popular Album": "Thalassic",
    "Top Song": "In My Sword I Trust",
    "2° Top Song": "One Man Army",
    "3° Top Song": "Lai Lai Hei",
    "4° Top Song": "Andromeda",
    "5° Top Song": "Twilight Tavern",
    "Spotify Listeners": "227913",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "SA"},

    {"ID": "039", 
    "Band Name" : "Equilibrium",
    "Genre" : "Epic Folk Metal", 
    "Year Formed": "2001",
    "Founded In": "Starnberg, DE",
    "Country": "Germany",
    "N° of Albums": "6",
    "N° of Singles": "6",
    "Newest Album": "Renegades",
    "Year": "2019",
    "N°1 Most Popular Album": "Armageddon",
    "2° Most Popular Album": "Erdentempel",
    "3° Most Popular Album": "Renegades",
    "Top Song": "Himmelsrand",
    "2° Top Song": "Born to Be Epic",
    "3° Top Song": "Revolution",
    "4° Top Song": "Blut im Ague",
    "5° Top Song": "Jhonny B",
    "Spotify Listeners": "428171",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "040", 
    "Band Name" : "Falkenbach",
    "Genre" : "Viking/Black/Folk Metal", 
    "Year Formed": "1989",
    "Founded In": "Düsseldrof, DE",
    "Country": "Germany",
    "N° of Albums": "6",
    "N° of Singles": "1",
    "Newest Album": "Asa",
    "Year": "2013",
    "N°1 Most Popular Album": "...en their medh riki fara...",
    "2° Most Popular Album": "...magni blandinn ok megintíri...",
    "3° Most Popular Album": "Tiurida",
    "Top Song": "Eweroun",
    "2° Top Song": "... Where His Ravens Fly ...",
    "3° Top Song": "Blout Fuër Bluot",
    "4° Top Song": "When Gjallarhorn Will Sound",
    "5° Top Song": "Vaer Stjernar Vaerdan",
    "Spotify Listeners": "32329",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "041", 
    "Band Name" : "Far Beyond",
    "Genre" : "Symphonic Melodic Death Metal", 
    "Year Formed": "2001",
    "Founded In": "Nurenberg, DE",
    "Country": "Germany",
    "N° of Albums": "2",
    "N° of Singles": "0",
    "Newest Album": "A Frozen Flame of Ice",
    "Year": "2016",
    "N°1 Most Popular Album": "A Frozen Flame of Ice",
    "2° Most Popular Album": "An Angel's Requiem",
    "3° Most Popular Album": "",
    "Top Song": "The Song Remains the Same",
    "2° Top Song": "A Frozen Flame of Ice",
    "3° Top Song": "Evernight, Pt. I",
    "4° Top Song": "Last Farewell",
    "5° Top Song": "Evernight, Pt. II",
    "Spotify Listeners": "560",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "042", 
    "Band Name" : "Fejd",
    "Genre" : "Folk Metal", 
    "Year Formed": "2001",
    "Founded In": "Lilla Edet, SE",
    "Country": "Sweden",
    "N° of Albums": "4",
    "N° of Singles": "2",
    "Newest Album": "Trolldom",
    "Year": "2016",
    "N°1 Most Popular Album": "Storm",
    "2° Most Popular Album": "Eifur",
    "3° Most Popular Album": "	Trolldom",
    "Top Song": "Härjaren",
    "2° Top Song": "Offrrok",
    "3° Top Song": "Den Skimrande",
    "4° Top Song": "Yggdrasil",
    "5° Top Song": "Dragen Och Krakan",
    "Spotify Listeners": "16963",
    "In tour?": "",
    "When?": "",
    "Where?": ""},

    {"ID": "043", 
    "Band Name" : "Finntroll",
    "Genre" : "Blackened Folk Metal", 
    "Year Formed": "1997",
    "Founded In": "Helsinki, FI",
    "Country": "Finland",
    "N° of Albums": "7",
    "N° of Singles": "3",
    "Newest Album": "Vredesvävd",
    "Year": "2020",
    "N°1 Most Popular Album": "Nifelvind",
    "2° Most Popular Album": "Blodsvept",
    "3° Most Popular Album": "Vredesvävd",
    "Top Song": "Trollhammaren",
    "2° Top Song": "Under Bergets Rot",
    "3° Top Song": "Ca You Forgive Her?",
    "4° Top Song": "Solsagan",
    "5° Top Song": "Blodsvept",
    "Spotify Listeners": "133062",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "044", 
    "Band Name" : "Finterfrost",
    "Genre" : "Folk/Viking Metal", 
    "Year Formed": "2004",
    "Founded In": "Freiburg, DE",
    "Country": "Germany",
    "N° of Albums": "5",
    "N° of Singles": "0",
    "Newest Album": "Zerfall",
    "Year": "2019",
    "N°1 Most Popular Album": "Zerfall",
    "2° Most Popular Album": "Weltenkraft",
    "3° Most Popular Album": "Mach dich frei",
    "Top Song": "Mach Dich Frei!",
    "2° Top Song": "Das Schlimmste Ist, Wenn Das Bier Alle Ist",
    "3° Top Song": "Bottle Gods",
    "4° Top Song": "Zerfall",
    "5° Top Song": "Des Waldes Macht",
    "Spotify Listeners": "29432",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "045", 
    "Band Name" : "Furor Gallico",
    "Genre" : "Folk Metal", 
    "Year Formed": "2007",
    "Founded In": "Monza, IT",
    "Country": "Italy",
    "N° of Albums": "3",
    "N° of Singles": "1",
    "Newest Album": "Dusk of the Ages",
    "Year": "2019",
    "N°1 Most Popular Album": "Dusk of the Ages",
    "2° Most Popular Album": "Furor Gallico",
    "3° Most Popular Album": "Songs from the Earth",
    "Top Song": "La caccia morta",
    "2° Top Song": "Canto Di Inverno",
    "3° Top Song": "Banshee",
    "4° Top Song": "Crumisagios",
    "5° Top Song": "Banshee",
    "Spotify Listeners": "25180",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "046", 
    "Band Name" : "Gallows End",
    "Genre" : "Heavy Metal", 
    "Year Formed": "2007",
    "Founded In": "Arvika, SE",
    "Country": "Sweden",
    "N° of Albums": "1",
    "N° of Singles": "0",
    "Newest Album": "Nemesis Divine",
    "Year": "2010",
    "N°1 Most Popular Album": "Nemesis Divine",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Soul Collector",
    "2° Top Song": "Kingdom of the Damned",
    "3° Top Song": "Nemesis Divine (Trial of the Gods)",
    "4° Top Song": "The Curse",
    "5° Top Song": "Set the World in Flames",
    "Spotify Listeners": "769",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "047", 
    "Band Name" : "Garmarna",
    "Genre" : "Folk Rock", 
    "Year Formed": "1990",
    "Founded In": "Sundsvall, SE",
    "Country": "Sweden",
    "N° of Albums": "7",
    "N° of Singles": "10",
    "Newest Album": "Förbundet",
    "Year": "2020",
    "N°1 Most Popular Album": "Guds Spelemän",
    "2° Most Popular Album": "Förbundet",
    "3° Most Popular Album": "Vedergällnigen",
    "Top Song": "Herr Mannelig",
    "2° Top Song": "Sven i Rosengård",
    "3° Top Song": "Nåden",
    "4° Top Song": "Vänner och Fränder",
    "5° Top Song": "Två Systrar",
    "Spotify Listeners": "152942",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "048", 
    "Band Name" : "Genus Ordinis Dei",
    "Genre" : "Symphonic Deat Metal/Groove/Metalcore", 
    "Year Formed": "2009",
    "Founded In": "Creama, IT",
    "Country": "Italy",
    "N° of Albums": "3",
    "N° of Singles": "3",
    "Newest Album": "Glare of Deliverance",
    "Year": "2020",
    "N°1 Most Popular Album": "Glare of Deliverance",
    "2° Most Popular Album": "Great Olden Dynasty",
    "3° Most Popular Album": "The Middle",
    "Top Song": "Hail and Kill",
    "2° Top Song": "Edict",
    "3° Top Song": "The Entropic Queen",
    "4° Top Song": "Salem",
    "5° Top Song": "Examination",
    "Spotify Listeners": "17263",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "049", 
    "Band Name" : "George Ezra",
    "Genre" : "Folk Pop/Blues", 
    "Year Formed": "2013",
    "Founded In": "London, UK",
    "Country": "United Kingdom",
    "N° of Albums": "3",
    "N° of Singles": "17",
    "Newest Album": "Gold Rush Kid",
    "Year": "2022",
    "N°1 Most Popular Album": "Wanted on Voyage",
    "2° Most Popular Album": "Gold Rush Kid",
    "3° Most Popular Album": "Staying at Tamara's",
    "Top Song": "Budapest",
    "2° Top Song": "Blame It on Me",
    "3° Top Song": "Shotgun",
    "4° Top Song": "Did You Hear The Tain?",
    "5° Top Song": "Green Green Grass",
    "Spotify Listeners": "15580412",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "050", 
    "Band Name" : "Gloryhammer",
    "Genre" : "Symphonic Power Metal", 
    "Year Formed": "2010",
    "Founded In": "Scotland, UK",
    "Country": "United Kingdom",
    "N° of Albums": "3",
    "N° of Singles": "3",
    "Newest Album": "Legends from Beyond the Galactic Terrorvortex",
    "Year": "2019",
    "N°1 Most Popular Album": "Space 1992: Rise of the Chaos Wizards",
    "2° Most Popular Album": "Legends from Beyond the Galactic Terrorvortex",
    "3° Most Popular Album": "Tales from the Kingdom of Fife",
    "Top Song": "Angus Mcfife",
    "2° Top Song": "Universe on Fire",
    "3° Top Song": "Fly Away",
    "4° Top Song": "Gloryhammer",
    "5° Top Song": "Hootsforce",
    "Spotify Listeners": "390141",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "051", 
    "Band Name" : "Grave Digger",
    "Genre" : "Heavy/Power Metal", 
    "Year Formed": "1980",
    "Founded In": "Gladbeck, DE",
    "Country": "Germany",
    "N° of Albums": "21",
    "N° of Singles": "14",
    "Newest Album": "Symbol of Eternity",
    "Year": "2022",
    "N°1 Most Popular Album": "The Devil Is a Gambler",
    "2° Most Popular Album": "Fields of Blood",
    "3° Most Popular Album": "Symbol Of Eternity",
    "Top Song": "Rebellion (The Clans are Marching)",
    "2° Top Song": "Zombie Dance",
    "3° Top Song": "Heart Of A Warrior",
    "4° Top Song": "Battle Cry",
    "5° Top Song": "The Ballad of Mary",
    "Spotify Listeners": "206325",
    "In tour?": "Yes",
    "When?": "2022/2023",
    "Where?": "EU"},

    {"ID": "052", 
    "Band Name" : "Great Vast Forest",
    "Genre" : "Black Metal", 
    "Year Formed": "1995",
    "Founded In": "Lages, BR",
    "Country": "Brazil",
    "N° of Albums": "2",
    "N° of Singles": "0",
    "Newest Album": "From the Dark Times to the Black Metal Legions",
    "Year": "2017",
    "N°1 Most Popular Album": "From the Dark Times to the Black Metal Legions",
    "2° Most Popular Album": "Battletales and Songs of Steel",
    "3° Most Popular Album": "",
    "Top Song": "Ride of the Valkyries",
    "2° Top Song": "Brave Blood Hero",
    "3° Top Song": "Prelude to the Victory on the Battlefield",
    "4° Top Song": "In the Deep Forests of Transylvania",
    "5° Top Song": "Memories of the Fire and Ice",
    "Spotify Listeners": "48",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "053", 
    "Band Name" : "Grimner",
    "Genre" : "Folk/Viking Metal", 
    "Year Formed": "2008",
    "Founded In": "motala, SE",
    "Country": "Sweden",
    "N° of Albums": "4",
    "N° of Singles": "9",
    "Newest Album": "Urfader",
    "Year": "2022",
    "N°1 Most Popular Album": "Vanadrottning",
    "2° Most Popular Album": "Frost mot eld",
    "3° Most Popular Album": "Urfader",
    "Top Song": "Eldhjärta",
    "2° Top Song": "En fallen jätte",
    "3° Top Song": "Freja Vakar",
    "4° Top Song": "Västerled",
    "5° Top Song": "Hinn heiðinn siðr",
    "Spotify Listeners": "24186",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "054", 
    "Band Name" : "HammerFall",
    "Genre" : "Heavy/Power Metal", 
    "Year Formed": "1993",
    "Founded In": "Gothenburg, SE",
    "Country": "Sweden",
    "N° of Albums": "12",
    "N° of Singles": "9",
    "Newest Album": "Hammer of Dawn",
    "Year": "2022",
    "N°1 Most Popular Album": "	Glory to the Brave",
    "2° Most Popular Album": "Legacy of Kings",
    "3° Most Popular Album": "Crimson Thunder",
    "Top Song": "Glory to the Brave",
    "2° Top Song": "Blood Bound",
    "3° Top Song": "Hearts on Fire",
    "4° Top Song": "last Man Standing",
    "5° Top Song": "Any Means Necessary",
    "Spotify Listeners": "1144506",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "055", 
    "Band Name" : "Heathen Foray",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "2004",
    "Founded In": "Graz, AT",
    "Country": "Austria",
    "N° of Albums": "5",
    "N° of Singles": "1",
    "Newest Album": "Weltenwandel",
    "Year": "2020",
    "N°1 Most Popular Album": "Inner Force",
    "2° Most Popular Album": "Armored Bards",
    "3° Most Popular Album": "Weltenwandel",
    "Top Song": "No Mercy",
    "2° Top Song": "Ragnarök",
    "3° Top Song": "Fight",
    "4° Top Song": "Armored Bards",
    "5° Top Song": "Tanz",
    "Spotify Listeners": "26796",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "056", 
    "Band Name" : "Heidevolk",
    "Genre" : "Folk/Viking Metal", 
    "Year Formed": "2002",
    "Founded In": "Arnhem, NL",
    "Country": "Netherlands",
    "N° of Albums": "6",
    "N° of Singles": "0",
    "Newest Album": "Vuur van verzet",
    "Year": "2018",
    "N°1 Most Popular Album": "Walhalla wacht",
    "2° Most Popular Album": "De strijdlust is geboren",
    "3° Most Popular Album": "Velua",
    "Top Song": "A Wolf in My Heart",
    "2° Top Song": "Yngwaz Zonen",
    "3° Top Song": "Nehalennia",
    "4° Top Song": "Saksenland",
    "5° Top Song": "Furor Teutonicus",
    "Spotify Listeners": "94063",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "057", 
    "Band Name" : "Heilung",
    "Genre" : "Neo Folk/Euro Ethnic", 
    "Year Formed": "2014",
    "Founded In": "Copenhagen, DE",
    "Country": "Denmark, Germany and Norway",
    "N° of Albums": "4",
    "N° of Singles": "0",
    "Newest Album": "Lifa",
    "Year": "2017",
    "N°1 Most Popular Album": "Futha",
    "2° Most Popular Album": "Drif",
    "3° Most Popular Album": "Ofnir",
    "Top Song": "Hakkerskaldyr",
    "2° Top Song": "Krigsgaldr",
    "3° Top Song": "Anona",
    "4° Top Song": "Norupo",
    "5° Top Song": "Svanrand",
    "Spotify Listeners": "526972",
    "In tour?": "Yes",
    "When?": "2022/2023",
    "Where?": "EU/US"},

    {"ID": "058", 
    "Band Name" : "Helloween",
    "Genre" : "Power/Speed Metal", 
    "Year Formed": "1983",
    "Founded In": "Hamburg, DE",
    "Country": "Germany",
    "N° of Albums": "18",
    "N° of Singles": "14",
    "Newest Album": "Helloween",
    "Year": "2021",
    "N°1 Most Popular Album": "The Time of the Oath",
    "2° Most Popular Album": "Straight Out of Hell",
    "3° Most Popular Album": "Masters of the Rings",
    "Top Song": "Forever and One",
    "2° Top Song": "If I Could Fly",
    "3° Top Song": "I Want Out",
    "4° Top Song": "In the Middle of a Heartbeat",
    "5° Top Song": "A Tale That Wasnt Rigth",
    "Spotify Listeners": "1300785",
    "In tour?": "Yes",
    "When?": "2023",
    "Where?": "EU"},

    {"ID": "059",
    "Band Name" : "Helroth",
    "Genre" : "Pagan/Folk Metal", 
    "Year Formed": "2012",
    "Founded In": "Warsaw, PL",
    "Country": "Poland",
    "N° of Albums": "1",
    "N° of Singles": "0",
    "Newest Album": "I, Pagan",
    "Year": "2016",
    "N°1 Most Popular Album": "I, Pagan",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Ortni",
    "2° Top Song": "Mamuny",
    "3° Top Song": "Kwiat",
    "4° Top Song": "Kwiat zycia",
    "5° Top Song": "Wilcza jagoda",
    "Spotify Listeners": "12751",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "060", 
    "Band Name" : "Hindarfjäll",
    "Genre" : "Neo Folk", 
    "Year Formed": "2019",
    "Founded In": "Stockholm, SE",
    "Country": "Sweden",
    "N° of Albums": "2",
    "N° of Singles": "0",
    "Newest Album": "Lärads Grenar",
    "Year": "Från Tidernas Begynnelse",
    "N°1 Most Popular Album": "Lärads Grenar",
    "2° Most Popular Album": "Från Tidernas Begynnelse",
    "3° Most Popular Album": "",
    "Top Song": "Så Som Träden Viskar Hans Namn",
    "2° Top Song": "Från Tidernas Begynnelse",
    "3° Top Song": "Sunnas Strålar",
    "4° Top Song": "Skogen Kallar Mig Hem",
    "5° Top Song": "Hjulet Vänder",
    "Spotify Listeners": "24735",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "061", 
    "Band Name" : "Hjelvik",
    "Genre" : "Viking/Heavy Metal", 
    "Year Formed": "2020",
    "Founded In": "Vikedal, NO ",
    "Country": "Norway",
    "N° of Albums": "1",
    "N° of Singles": "1",
    "Newest Album": "Welcome to Hel",
    "Year": "2020",
    "N°1 Most Popular Album": "Welcome to Hel",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Glory to Hel",
    "2° Top Song": "Father War",
    "3° Top Song": "North Tsar",
    "4° Top Song": "The Power Ballad of Freyr",
    "5° Top Song": "Thors Hammer",
    "Spotify Listeners": "2398",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "062", 
    "Band Name" : "Heljareyga",
    "Genre" : "Folk/Progressive Metal", 
    "Year Formed": "Runavík, FO ",
    "Founded In": "2009",
    "Country": "Faroe Islands/Denmark",
    "N° of Albums": "1",
    "N° of Singles": "0",
    "Newest Album": "Heljareyga",
    "Year": "2010",
    "N°1 Most Popular Album": "Heljareyga",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Regnið",
    "2° Top Song": "Heljareyga",
    "3° Top Song": "Feigdin",
    "4° Top Song": "Vetrarbreytin",
    "5° Top Song": "Lagnan",
    "Spotify Listeners": "343",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "063", 
    "Band Name" : "Helgrindur",
    "Genre" : "Pagan Metal", 
    "Year Formed": "2009",
    "Founded In": "Solingen, DE",
    "Country": "Germany",
    "N° of Albums": "1",
    "N° of Singles": "0",
    "Newest Album": "Von einst",
    "Year": "2017",
    "N°1 Most Popular Album": "Von einst",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Grimus Fluch",
    "2° Top Song": "Gotenzug",
    "3° Top Song": "Von Einst",
    "4° Top Song": "Aufbruch",
    "5° Top Song": "Lügenbold",
    "Spotify Listeners": "200",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "064", 
    "Band Name" : "Hozier",
    "Genre" : "Blues/Rock", 
    "Year Formed": "2008",
    "Founded In": "Dublin, IE",
    "Country": "Ireland",
    "N° of Albums": "2",
    "N° of Singles": "18",
    "Newest Album": "Wasteland, Baby",
    "Year": "2019",
    "N°1 Most Popular Album": "Hozier",
    "2° Most Popular Album": "Wasteland, Baby",
    "3° Most Popular Album": "",
    "Top Song": "Take Me To Church",
    "2° Top Song": "Tell It To My Heart",
    "3° Top Song": "Cherry Wine",
    "4° Top Song": "Like Real People Do",
    "5° Top Song": "Someone New",
    "Spotify Listeners": "20400484",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "065", 
    "Band Name" : "Human Fortress",
    "Genre" : "Epic Power Metal", 
    "Year Formed": "1999",
    "Founded In": "Hanover, DE",
    "Country": "Germany",
    "N° of Albums": "6",
    "N° of Singles": "0",
    "Newest Album": "Regin of Gold",
    "Year": "2019",
    "N°1 Most Popular Album": "Lord of Earth and Heavens Heir",
    "2° Most Popular Album": "Defenders of the Crown",
    "3° Most Popular Album": "Raided Land",
    "Top Song": "Defenders of the Crown",
    "2° Top Song": "Dark Knight",
    "3° Top Song": "Thunder",
    "4° Top Song": "Knights in Shining Armour",
    "5° Top Song": "Raided Land",
    "Spotify Listeners": "34461",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "066", 
    "Band Name" : "Iced Earth",
    "Genre" : "Power/Trash Metal", 
    "Year Formed": "1988",
    "Founded In": "Tampa, US",
    "Country": "United States",
    "N° of Albums": "14",
    "N° of Singles": "8",
    "Newest Album": "A Narrative Soundscape",
    "Year": "2022",
    "N°1 Most Popular Album": "The Dark Saga",
    "2° Most Popular Album": "Something Wicked This Way Comes",
    "3° Most Popular Album": "Horror Show",
    "Top Song": "Watching over Me",
    "2° Top Song": "Melancholy",
    "3° Top Song": "Ghost of Freedom",
    "4° Top Song": "Anthem",
    "5° Top Song": "I Died For You",
    "Spotify Listeners": "324487",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "067", 
    "Band Name" : "Imago Imperii",
    "Genre" : "Symphonic Power Metal", 
    "Year Formed": "2011",
    "Founded In": "Bologna, IT",
    "Country": "Italy",
    "N° of Albums": "3",
    "N° of Singles": "0",
    "Newest Album": "A Tale of Darkness and Hope",
    "Year": "2021",
    "N°1 Most Popular Album": "A Tale of Darkness and Hope",
    "2° Most Popular Album": "Fate of a King",
    "3° Most Popular Album": "Legendaria",
    "Top Song": "Look at the Stars",
    "2° Top Song": "Last Queen MMXXI",
    "3° Top Song": "Kingodms United",
    "4° Top Song": "Battle at Stamford Bridge",
    "5° Top Song": "The Accusation",
    "Spotify Listeners": "46",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "068", 
    "Band Name" : "In Extremo",
    "Genre" : "Medieval Metal/Folk Metal", 
    "Year Formed": "1995",
    "Founded In": "Berlin, DE",
    "Country": "Germany",
    "N° of Albums": "12",
    "N° of Singles": "14",
    "Newest Album": "Kompass zur Sonne",
    "Year": "2020",
    "N°1 Most Popular Album": "Kompass zur Sonne",
    "2° Most Popular Album": "Kunstraub",
    "3° Most Popular Album": "Sterneneisen",
    "Top Song": "Kompass zur Sonne",
    "2° Top Song": "Lügenpack",
    "3° Top Song": "Reiht euch ein ihr Lumpen",
    "4° Top Song": "Troja",
    "5° Top Song": "Gogiya",
    "Spotify Listeners": "367871",
    "In tour?": "Yes",
    "When?": "",
    "Where?": "EU"},

    {"ID": "069", 
    "Band Name" : "Ivar Bjørnson & Einar Selvik",
    "Genre" : "Neofolk", 
    "Year Formed": "2014",
    "Founded In": "Bergen, NO",
    "Country": "Norway",
    "N° of Albums": "2",
    "N° of Singles": "1",
    "Newest Album": "Hugsjá",
    "Year": "2018",
    "N°1 Most Popular Album": "Skuggsjá",
    "2° Most Popular Album": "Hugsjá",
    "3° Most Popular Album": "",
    "Top Song": "Hugsjá",
    "2° Top Song": "Kvervandi",
    "3° Top Song": "Skuggsjá",
    "4° Top Song": "Um Heilage Fjell",
    "5° Top Song": "Rop frå røynda - mælt frå minne",
    "Spotify Listeners": "105432",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "070", 
    "Band Name" : "Kaunan",
    "Genre" : "Neo Folk", 
    "Year Formed": "2017",
    "Founded In": "Stockholm, SE",
    "Country": "Sweden",
    "N° of Albums": "1",
    "N° of Singles": "3",
    "Newest Album": "Forn",
    "Year": "2017",
    "N°1 Most Popular Album": "Forn",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Vallåt",
    "2° Top Song": "Halteguten",
    "3° Top Song": "Polska Svit",
    "4° Top Song": "Den Gamle Sordølen",
    "5° Top Song": "Svärdsjö Polska",
    "Spotify Listeners": "31554",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "071", 
    "Band Name" : "King of Asgard",
    "Genre" : "Viking/Melodic Death Metal", 
    "Year Formed": "2008",
    "Founded In": "Mjölby, SE",
    "Country": "Sweden",
    "N° of Albums": "5",
    "N° of Singles": "1",
    "Newest Album": "Svartrviðr",
    "Year": "2021",
    "N°1 Most Popular Album": "Fi'mbulvintr",
    "2° Most Popular Album": "Karg",
    "3° Most Popular Album": "Svartrviðr",
    "Top Song": "Einharjar",
    "2° Top Song": "The Nine Worlds Burn",
    "3° Top Song": "Nordvegr",
    "4° Top Song": "The Runes of Hel",
    "5° Top Song": "The Last Journy",
    "Spotify Listeners": "11333",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "072", 
    "Band Name" : "Korpiklaani",
    "Genre" : "Folk Metal", 
    "Year Formed": "2003",
    "Founded In": "Lahti, FI",
    "Country": "Finland",
    "N° of Albums": "11",
    "N° of Singles": "18",
    "Newest Album": "Jylhä",
    "Year": "2021",
    "N°1 Most Popular Album": "Manala",
    "2° Most Popular Album": "Noita",
    "3° Most Popular Album": "Karkelo",
    "Top Song": "Lempo",
    "2° Top Song": "Vodka",
    "3° Top Song": "Levan Polkka",
    "4° Top Song": "A Man with a Plan",
    "5° Top Song": "Viinamäen Mies",
    "Spotify Listeners": "683177",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "073", 
    "Band Name" : "Lonewolf",
    "Genre" : "Speed Metal", 
    "Year Formed": "1992",
    "Founded In": "Claix, FR",
    "Country": "France",
    "N° of Albums": "10",
    "N° of Singles": "3",
    "Newest Album": "Division Hades",
    "Year": "2020",
    "N°1 Most Popular Album": "The Heathen Dawn",
    "2° Most Popular Album": "Raised on Metal",
    "3° Most Popular Album": "Cult of Steel",
    "Top Song": "Untill the End",
    "2° Top Song": "Wolsblut",
    "3° Top Song": "Trough FIre, Ice and Blood",
    "4° Top Song": "Raised on Metal",
    "5° Top Song": "underground Warriors",
    "Spotify Listeners": "7949",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "US"},

    {"ID": "074", 
    "Band Name" : "Lumsk",
    "Genre" : "Folk Metal", 
    "Year Formed": "1999",
    "Founded In": "Trondheim, NO",
    "Country": "Norway",
    "N° of Albums": "3",
    "N° of Singles": "2",
    "Newest Album": "Det vilde kor",
    "Year": "2007",
    "N°1 Most Popular Album": "Åsmund Frægdegjevar",
    "2° Most Popular Album": "Det vilde kor",
    "3° Most Popular Album": "Troll",
    "Top Song": "Ormin Lange",
    "2° Top Song": "I trollehender",
    "3° Top Song": "Om hundrede aar er alting glemt",
    "4° Top Song": "Dunker",
    "5° Top Song": "Trolltind",
    "Spotify Listeners": "10604",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "075", 
    "Band Name" : "Mærer",
    "Genre" : "Black/Doom Metal", 
    "Year Formed": "2019",
    "Founded In": "Halle, DE",
    "Country": "Germany",
    "N° of Albums": "0",
    "N° of Singles": "3",
    "Newest Album": "",
    "Year": "",
    "N°1 Most Popular Album": "",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "I / IV - Vom Ende",
    "2° Top Song": "II / IV - Jener Zeiten",
    "3° Top Song": "III / IV - Verfasstes Leiden",
    "4° Top Song": "IV / IV - Im Buche die letzten Zeilen",
    "5° Top Song": "",
    "Spotify Listeners": "408",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "076", 
    "Band Name" : "Månegarm",
    "Genre" : "Viking/Black/Folk Metal", 
    "Year Formed": "1995",
    "Founded In": "Norrtälje, SE",
    "Country": "Sweden",
    "N° of Albums": "10",
    "N° of Singles": "1",
    "Newest Album": "Ynglingaättens öde",
    "Year": "2022",
    "N°1 Most Popular Album": "Vargstenen",
    "2° Most Popular Album": "Dödsfärd",
    "3° Most Popular Album": "Månegarm",
    "Top Song": "Odin Owns Ye All",
    "2° Top Song": "Nattsjäl, drömsjäl",
    "3° Top Song": "Hemfärd",
    "4° Top Song": "Blodörn",
    "5° Top Song": "En snara av guld",
    "Spotify Listeners": "43834",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "077", 
    "Band Name" : "Manowar",
    "Genre" : "Heavy/Power Metal", 
    "Year Formed": "1980",
    "Founded In": "Auburn, US",
    "Country": "United States",
    "N° of Albums": "13",
    "N° of Singles": "14",
    "Newest Album": "Kings of Metal MMXIV",
    "Year": "2014",
    "N°1 Most Popular Album": "Kings of Metal",
    "2° Most Popular Album": "Fighting the World",
    "3° Most Popular Album": "Battle Hymns",
    "Top Song": "Hail and Kill",
    "2° Top Song": "Kings of Metal",
    "3° Top Song": "Fighting the World",
    "4° Top Song": "Heart of Steel",
    "5° Top Song": "Battle Hymn",
    "Spotify Listeners": "866009",
    "In tour?": "Yes",
    "When?": "2023",
    "Where?": "EU"},

    {"ID": "078", 
    "Band Name" : "Medieval Rites",
    "Genre" : "Medieval Ambient/Orchestral", 
    "Year Formed": "",
    "Founded In": "",
    "Country": "",
    "N° of Albums": "26",
    "N° of Singles": "0",
    "Newest Album": "Yggdrasil> The World Tree",
    "Year": "2021",
    "N°1 Most Popular Album": "Poetic Edda Winds of the North",
    "2° Most Popular Album": "Poetic Edda Norsemen Tales",
    "3° Most Popular Album": "Valhalla",
    "Top Song": "Frigga, Goddess of Marriage and Prophecy",
    "2° Top Song": "Epic Viking Battle Music",
    "3° Top Song": "Brighid, Hearth Goddess of Ireland",
    "4° Top Song": "Playing Bards",
    "5° Top Song": "Hel, Godess of the Underworld",
    "Spotify Listeners": "788",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "079", 
    "Band Name" : "Menhir",
    "Genre" : "Pagan Black Metal", 
    "Year Formed": "1995",
    "Founded In": "Breitungen, DE",
    "Country": "Germany",
    "N° of Albums": "4",
    "N° of Singles": "0",
    "Newest Album": "Hildebrandslied",
    "Year": "2017",
    "N°1 Most Popular Album": "Hildebrandslied",
    "2° Most Popular Album": "	Ziuwari",
    "3° Most Popular Album": "Thuringia",
    "Top Song": "Das Hilderbrandslied Teil 1",
    "2° Top Song": "Das alte Lied des Windes",
    "3° Top Song": "Das Hilderbrandslied Teil 2",
    "4° Top Song": "Wotans Runenlied",
    "5° Top Song": "Weit in der Ferne",
    "Spotify Listeners": "1482",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "080", 
    "Band Name" : "Mistur",
    "Genre" : "Folk/Viking/Black Metal", 
    "Year Formed": "2003",
    "Founded In": "Kaupanger, NO",
    "Country": "Norway",
    "N° of Albums": "2",
    "N° of Singles": "1",
    "Newest Album": "In Memoriam",
    "Year": "2016",
    "N°1 Most Popular Album": "Attende",
    "2° Most Popular Album": "In Memoriam",
    "3° Most Popular Album": "",
    "Top Song": "Downfall",
    "2° Top Song": "Matriarchs Lament",
    "3° Top Song": "The SIght",
    "4° Top Song": "Distant Peaks",
    "5° Top Song": "Attende",
    "Spotify Listeners": "4626",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "081", 
    "Band Name" : "My Dying Bride",
    "Genre" : "Doom Metal", 
    "Year Formed": "1990",
    "Founded In": "Halifax, UK",
    "Country": "United Kingdom",
    "N° of Albums": "12",
    "N° of Singles": "14",
    "Newest Album": "The Ghost of Orion",
    "Year": "2020",
    "N°1 Most Popular Album": "The Ghost of Orion",
    "2° Most Popular Album": "Feel the Misery",
    "3° Most Popular Album": "Songs Of Darkness, Words Of Light",
    "Top Song": "Your Broken Shore",
    "2° Top Song": "My Wine In Silence",
    "3° Top Song": "And My Father Left Forever",
    "4° Top Song": "For My Fallen Angel",
    "5° Top Song": "A Secret Kiss",
    "Spotify Listeners": "76625",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "082", 
    "Band Name" : "Myrkgrav",
    "Genre" : "Blackened Folk/Viking Metal", 
    "Year Formed": "2003",
    "Founded In": "Åsa, NO",
    "Country": "Norway",
    "N° of Albums": "2",
    "N° of Singles": "2",
    "Newest Album": "Takk og farvel; tida er blitt ei annen",
    "Year": "2016",
    "N°1 Most Popular Album": "Takk og farvel; tida er blitt ei annen",
    "2° Most Popular Album": "Trollskau, skrømt og kølabrenning",
    "3° Most Popular Album": "",
    "Top Song": "Skjøn jomfru",
    "2° Top Song": "Om å danse bekhette",
    "3° Top Song": "Spålsnatt",
    "4° Top Song": "Tørrhard",
    "5° Top Song": "Tre skygger tel kølabrennern kom",
    "Spotify Listeners": "19144",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "083", 
    "Band Name" : "Nomans Land",
    "Genre" : "Viking Metal", 
    "Year Formed": "1996",
    "Founded In": "St. Petersburg, RU ",
    "Country": "Russia",
    "N° of Albums": "5",
    "N° of Singles": "2",
    "Newest Album": "Last Crusade",
    "Year": "2015",
    "N°1 Most Popular Album": "Last Crusade",
    "2° Most Popular Album": "Farnord",
    "3° Most Popular Album": "Raven Flight",
    "Top Song": "Victory Horns",
    "2° Top Song": "Sons of the Nord",
    "3° Top Song": "Right to Luck",
    "4° Top Song": "Valkyrie",
    "5° Top Song": "Strains at the Oars",
    "Spotify Listeners": "944",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "084", 
    "Band Name" : "Northland",
    "Genre" : "Folk/Melodic Death", 
    "Year Formed": "2004",
    "Founded In": "Barcelona, ES",
    "Country": "Spain",
    "N° of Albums": "2",
    "N° of Singles": "0",
    "Newest Album": "Downfall and Rebirth",
    "Year": "2015",
    "N°1 Most Popular Album": "Northland",
    "2° Most Popular Album": "Downfall and Rebirth",
    "3° Most Popular Album": "",
    "Top Song": "When Nature Awakes",
    "2° Top Song": "Bloodred Sunrise",
    "3° Top Song": "Together We Die",
    "4° Top Song": "Moonslight Spell",
    "5° Top Song": "Spirit in Darkness",
    "Spotify Listeners": "11092",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "085", 
    "Band Name" : "Nothgard",
    "Genre" : "Epic Melodic Death", 
    "Year Formed": "2009",
    "Founded In": "Deggend, DE",
    "Country": "Germany",
    "N° of Albums": "5",
    "N° of Singles": "3",
    "Newest Album": "Malady X",
    "Year": "2018",
    "N°1 Most Popular Album": "Warhorns of Midgard",
    "2° Most Popular Album": "The Sinner's Sake",
    "3° Most Popular Album": "Age of Pandora",
    "Top Song": "Lightcrawler",
    "2° Top Song": "Malady X",
    "3° Top Song": "Epitaph",
    "4° Top Song": "Dominion of Cain",
    "5° Top Song": "Age of Pandora",
    "Spotify Listeners": "24166",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "086", 
    "Band Name" : "Orden Ogan",
    "Genre" : "Power Metal", 
    "Year Formed": "1996",
    "Founded In": "Arnsberg, DE",
    "Country": "Germany",
    "N° of Albums": "7",
    "N° of Singles": "18",
    "Newest Album": "Final Days",
    "Year": "2021",
    "N°1 Most Popular Album": "Ravenhead",
    "2° Most Popular Album": "Gunmen",
    "3° Most Popular Album": "To the End",
    "Top Song": "Gunman",
    "2° Top Song": "F.E.V.E.R",
    "3° Top Song": "Come with Me to the Other Side",
    "4° Top Song": "The Things We Belive In",
    "5° Top Song": "Heart of the Android",
    "Spotify Listeners": "309844",
    "In tour?": "Yes",
    "When?": "2022/2023",
    "Where?": "EU"},

    {"ID": "087", 
    "Band Name" : "Percival",
    "Genre" : "Epic Heavy Metal", 
    "Year Formed": "2015",
    "Founded In": "Buenos Aires, AR",
    "Country": "Argentina",
    "N° of Albums": "1",
    "N° of Singles": "1",
    "Newest Album": "Riders of the Sun",
    "Year": "2021",
    "N°1 Most Popular Album": "Riders of the Sun",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Riders of the Sun",
    "2° Top Song": "Twilight of the Gods",
    "3° Top Song": "Across the Sea",
    "4° Top Song": "Raise Your Arms",
    "5° Top Song": "Defender of Troy",
    "Spotify Listeners": "508",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "088", 
    "Band Name" : "Phönix",
    "Genre" : "Historic Metal", 
    "Year Formed": "",
    "Founded In": ", DE",
    "Country": "Germany",
    "N° of Albums": "2",
    "N° of Singles": "0",
    "Newest Album": "Germania",
    "Year": "2016",
    "N°1 Most Popular Album": "PflichterfüllungI",
    "2° Most Popular Album": "Germania",
    "3° Most Popular Album": "",
    "Top Song": "PflichterfüllungI",
    "2° Top Song": "Germania",
    "3° Top Song": "Panzer vor",
    "4° Top Song": "Wir sind im Krieg",
    "5° Top Song": "Rückschritt ist Fortschritt",
    "Spotify Listeners": "21488",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "089", 
    "Band Name" : "Feindnah",
    "Genre" : "Historic Metal", 
    "Year Formed": "",
    "Founded In": ",DE",
    "Country": "Germany",
    "N° of Albums": "2",
    "N° of Singles": "",
    "Newest Album": "Avantgarde",
    "Year": "2021",
    "N°1 Most Popular Album": "Odyssee",
    "2° Most Popular Album": "Avantgarde",
    "3° Most Popular Album": "",
    "Top Song": "Mann gegen Mann",
    "2° Top Song": "Wie Brüder",
    "3° Top Song": "Ahnenband",
    "4° Top Song": "Avantgarde",
    "5° Top Song": "Fahnenträger",
    "Spotify Listeners": "4082",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "090", 
    "Band Name" : "Übermensch",
    "Genre" : "Metalcore/Historic Metal", 
    "Year Formed": "",
    "Founded In": ",DE",
    "Country": "Germany",
    "N° of Albums": "",
    "N° of Singles": "",
    "Newest Album": "",
    "Year": "",
    "N°1 Most Popular Album": "Schicksalsgemeinschaft",
    "2° Most Popular Album": "Naturgewalt",
    "3° Most Popular Album": "Der Visionär",
    "Top Song": "Stillstand",
    "2° Top Song": "Heil Dir!",
    "3° Top Song": "Schicksalsgemeinschaft",
    "4° Top Song": "Deutsches Herz",
    "5° Top Song": "In Anerkennung",
    "Spotify Listeners": "30936",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "091", 
    "Band Name" : "Lass Leben",
    "Genre" : "Historic Metal", 
    "Year Formed": "",
    "Founded In": ",DE",
    "Country": "Germany",
    "N° of Albums": "1",
    "N° of Singles": "",
    "Newest Album": "Nordwaerts",
    "Year": "2020",
    "N°1 Most Popular Album": "Nordwaerts",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Große Zeit",
    "2° Top Song": "Bomben des Friedens",
    "3° Top Song": "Nordwaerts",
    "4° Top Song": "Hinaus zur See",
    "5° Top Song": "Muede Augen",
    "Spotify Listeners": "24566",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "092", 
    "Band Name" : "Skjaldar",
    "Genre" : "Pagan Metal", 
    "Year Formed": "2011",
    "Founded In": "Bayereuth, DE",
    "Country": "Germany",
    "N° of Albums": "2",
    "N° of Singles": "0",
    "Newest Album": "Re:vision",
    "Year": "2018",
    "N°1 Most Popular Album": "Weltenbruch",
    "2° Most Popular Album": "Re:vison",
    "3° Most Popular Album": "",
    "Top Song": "Fest der Ahnen",
    "2° Top Song": "Alter Wächter",
    "3° Top Song": "Skadi",
    "4° Top Song": "Monument des Schattens",
    "5° Top Song": "Niedergang",
    "Spotify Listeners": "36",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "093", 
    "Band Name" : "Hunde des Krieges",
    "Genre" : "Historic Metal", 
    "Year Formed": "2012",
    "Founded In": "Mönchengladbach, DE",
    "Country": "Germany",
    "N° of Albums": "1",
    "N° of Singles": "0",
    "Newest Album": "Frontschweine",
    "Year": "2014",
    "N°1 Most Popular Album": "Frontschweine",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "So weit die Füße tragen",
    "2° Top Song": "Mut, Ehre, Loyalität",
    "3° Top Song": "Wuot (Furor Teutonicus)",
    "4° Top Song": "Hunde des Krieges",
    "5° Top Song": "Der Toten Wort",
    "Spotify Listeners": "48127",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "094", 
    "Band Name" : "Ghost",
    "Genre" : "Heavy Metal/Rock", 
    "Year Formed": "2006",
    "Founded In": "Linköping, SE",
    "Country": "Sweden",
    "N° of Albums": "5",
    "N° of Singles": "16",
    "Newest Album": "Impera",
    "Year": "2022",
    "N°1 Most Popular Album": "Meliora",
    "2° Most Popular Album": "Impera",
    "3° Most Popular Album": "Ceremony And Devotion",
    "Top Song": "mary On A Cross",
    "2° Top Song": "Call Me Little Sunshine",
    "3° Top Song": "Kiss The Go-Goat",
    "4° Top Song": "Spillways",
    "5° Top Song": "Square Hammer",
    "Spotify Listeners": "9142151",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "NA"},

    {"ID": "095", 
    "Band Name" : "Powerwolf",
    "Genre" : "Power Metal", 
    "Year Formed": "2004",
    "Founded In": "Saarbrüchen, DE",
    "Country": "Germany",
    "N° of Albums": "10",
    "N° of Singles": "18",
    "Newest Album": "Call of the Wild",
    "Year": "2021",
    "N°1 Most Popular Album": "Bible of the Beast",
    "2° Most Popular Album": "Blessed & Possesed",
    "3° Most Popular Album": "Blood of the Saints",
    "Top Song": "We Drink Your Blood",
    "2° Top Song": "Army of the Night",
    "3° Top Song": "Sanctified with Dynamite",
    "4° Top Song": "Demons Are a Girls Best Friend",
    "5° Top Song": "Night of the Werewolves",
    "Spotify Listeners": "1264665",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "096", 
    "Band Name" : "Prima Nocta",
    "Genre" : "Neo Folk", 
    "Year Formed": "",
    "Founded In": ", BE",
    "Country": "Belgium",
    "N° of Albums": "4",
    "N° of Singles": "0",
    "Newest Album": "Flag of the Greenman",
    "Year": "2021",
    "N°1 Most Popular Album": "Lost in Time",
    "2° Most Popular Album": "Nocturnal Dawn",
    "3° Most Popular Album": "Moonshine",
    "Top Song": "Ötzi",
    "2° Top Song": "Stones and Metal",
    "3° Top Song": "Baudica",
    "4° Top Song": "Fenrir",
    "5° Top Song": "Spirits of the Woods",
    "Spotify Listeners": "21382",
    "In tour?": "",
    "When?": "",
    "Where?": ""},

    {"ID": "097", 
    "Band Name" : "Rebellion",
    "Genre" : "Heavy/Power Metal", 
    "Year Formed": "2001",
    "Founded In": "Frankfurt, DE",
    "Country": "Germany",
    "N° of Albums": "9",
    "N° of Singles": "3",
    "Newest Album": "We Are the People",
    "Year": "2021",
    "N°1 Most Popular Album": "Arise: From Ginnungagap to Ragnarök - The History of the Vikings Volume III",
    "2° Most Popular Album": "Miklagard - The History of the Vikings - Volume II	",
    "3° Most Popular Album": "Sagas of Iceland - The History of the Vikings - Volume I",
    "Top Song": "The Clans Are Marching",
    "2° Top Song": "Arise",
    "3° Top Song": "God of Thunder",
    "4° Top Song": "Sweden",
    "5° Top Song": "VI Seglar Mot Miklagard",
    "Spotify Listeners": "55411",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "098", 
    "Band Name" : "Rúnahild",
    "Genre" : "Folk", 
    "Year Formed": "",
    "Founded In": ",NO",
    "Country": "Norway",
    "N° of Albums": "7",
    "N° of Singles": "0",
    "Newest Album": "Wounded Healer",
    "Year": "2020",
    "N°1 Most Popular Album": "Seidfylgjur",
    "2° Most Popular Album": "Sedsang",
    "3° Most Popular Album": "Seidrúnar",
    "Top Song": "Seidrünar",
    "2° Top Song": "Seidfylgjur",
    "3° Top Song": "Fra Stjerner Til Jorda",
    "4° Top Song": "Ørnedans",
    "5° Top Song": "The Flight",
    "Spotify Listeners": "32442",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "099", 
    "Band Name" : "Stormwarrior",
    "Genre" : "Power Metal", 
    "Year Formed": "1998",
    "Founded In": "Hamburg, DE",
    "Country": "Germany",
    "N° of Albums": "6",
    "N° of Singles": "2",
    "Newest Album": "Norsemen",
    "Year": "2019",
    "N°1 Most Popular Album": "Thunder & Steele",
    "2° Most Popular Album": "Northern Rage",
    "3° Most Popular Album": "Heading Northe",
    "Top Song": "Heading Northe",
    "2° Top Song": "Ragnarök",
    "3° Top Song": "Metal Legacy",
    "4° Top Song": "Heathen Warrior",
    "5° Top Song": "Iron Gods",
    "Spotify Listeners": "46772",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "100", 
    "Band Name" : "Svartsot",
    "Genre" : "Folk Metal", 
    "Year Formed": "2005",
    "Founded In": "Randers, DE",
    "Country": "Denmark",
    "N° of Albums": "5",
    "N° of Singles": "1",
    "Newest Album": "Kumbl",
    "Year": "2022",
    "N°1 Most Popular Album": "Ravnenes saga",
    "2° Most Popular Album": "Mulmets viser",
    "3° Most Popular Album": "Vældet",
    "Top Song": "Gravollet",
    "2° Top Song": "Midsommer",
    "3° Top Song": "Drømte mig en drøm",
    "4° Top Song": "Rottefængeren",
    "5° Top Song": "Tvende Ravne",
    "Spotify Listeners": "17894",
    "In tour?": "Yes",
    "When?": "2023",
    "Where?": "EU"},

    {"ID": "101", 
    "Band Name" : "Thrudvangar",
    "Genre" : "Viking Black Metal", 
    "Year Formed": "2000",
    "Founded In": "Köthen, DE",
    "Country": "Germany",
    "N° of Albums": "6",
    "N° of Singles": "1",
    "Newest Album": "Vegvisir",
    "Year": "2020",
    "N°1 Most Popular Album": "Zwischen Asgard und Midgard",
    "2° Most Popular Album": "Zwischen Asgard und Midgard",
    "3° Most Popular Album": "Walhall",
    "Top Song": "Sonnenwende",
    "2° Top Song": "Tiwaz",
    "3° Top Song": "Jörmungandr",
    "4° Top Song": "Wächter Der Brüche",
    "5° Top Song": "Segvaters Maid",
    "Spotify Listeners": "2968",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "102", 
    "Band Name" : "Thyrfing",
    "Genre" : "Viking Black Metal", 
    "Year Formed": "1995",
    "Founded In": "Stockholm, SE",
    "Country": "Sweden",
    "N° of Albums": "8",
    "N° of Singles": "3",
    "Newest Album": "Vanagandr",
    "Year": "2021",
    "N°1 Most Popular Album": "De ödeslösa",
    "2° Most Popular Album": "Vansinnesvisor",
    "3° Most Popular Album": "Farsotstider",
    "Top Song": "Mjölner",
    "2° Top Song": "The Voyager",
    "3° Top Song": "Döp dem i eld",
    "4° Top Song": "Draugs Harg",
    "5° Top Song": "Digerdöden",
    "Spotify Listeners": "17036",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "103", 
    "Band Name" : "Týr",
    "Genre" : "Folk Metal", 
    "Year Formed": "1998",
    "Founded In": "Copenhagen, DE",
    "Country": "Denmark/Faroe Islands",
    "N° of Albums": "8",
    "N° of Singles": "0",
    "Newest Album": "Hel",
    "Year": "2019",
    "N°1 Most Popular Album": "By the Light of the Northern Star",
    "2° Most Popular Album": "Eric the Red",
    "3° Most Popular Album": "Ragnarok",
    "Top Song": "Blood of Hereos",
    "2° Top Song": "Hold the Heathen Hammer High",
    "3° Top Song": "By the Sword in My Hand",
    "4° Top Song": "Ragnars kvæði ",
    "5° Top Song": "Cementery Gates",
    "Spotify Listeners": "210517",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "104", 
    "Band Name" : "Valhalore",
    "Genre" : "Epic Folk/Viking Metal", 
    "Year Formed": "2013",
    "Founded In": "Brisbane, AU",
    "Country": "Australia",
    "N° of Albums": "1",
    "N° of Singles": "4",
    "Newest Album": "Voyage into Eternity",
    "Year": "2020",
    "N°1 Most Popular Album": "Voyage into Eternity",
    "2° Most Popular Album": "",
    "3° Most Popular Album": "",
    "Top Song": "Legacy",
    "2° Top Song": "Solitude",
    "3° Top Song": "Guardians of Time",
    "4° Top Song": "A Rose for Epona",
    "5° Top Song": "The Bards Song",
    "Spotify Listeners": "27633",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "AU"},

    {"ID": "104", 
    "Band Name" : "Valonkantajat",
    "Genre" : "Melodic Heavy Metal", 
    "Year Formed": "2010",
    "Founded In": "Riihimäki, FI",
    "Country": "Finland",
    "N° of Albums": "3",
    "N° of Singles": "6",
    "Newest Album": "Vastavirtaan",
    "Year": "2017",
    "N°1 Most Popular Album": "Tuomittu elämään",
    "2° Most Popular Album": "Vastavirtaan",
    "3° Most Popular Album": "Pimentola",
    "Top Song": "Tuomittu Elämään",
    "2° Top Song": "Katso Maailmaa, Se Palaa",
    "3° Top Song": "Rakkaasi Kadotat",
    "4° Top Song": "Tavoitinjo Taivaan",
    "5° Top Song": "Raskas Päivä Päättyy",
    "Spotify Listeners": "5531",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "105", 
    "Band Name" : "Vanir",
    "Genre" : "Viking/Folk Metal", 
    "Year Formed": "2009",
    "Founded In": "Roskilde, DK",
    "Country": "Denmark",
    "N° of Albums": "6",
    "N° of Singles": "8",
    "Newest Album": "Sagas",
    "Year": "2022",
    "N°1 Most Popular Album": "Aldar Rök",
    "2° Most Popular Album": "Allfather",
    "3° Most Popular Album": "Særimners kød",
    "Top Song": "Sons of the North",
    "2° Top Song": "Raise Your Horns",
    "3° Top Song": "Af Brages æt",
    "4° Top Song": "Dark Clouds Gather",
    "5° Top Song": "By The Hammer They Fall",
    "Spotify Listeners": "29631",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "106", 
    "Band Name" : "Varg",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "2005",
    "Founded In": "Coburg, DE",
    "Country": "Germany",
    "N° of Albums": "7",
    "N° of Singles": "0",
    "Newest Album": "Zeichen",
    "Year": "2020",
    "N°1 Most Popular Album": "Wolfszeit II",
    "2° Most Popular Album": "Das Ende aller Lügen",
    "3° Most Popular Album": "Wolfszeit",
    "Top Song": "Achtung",
    "2° Top Song": "Schwertzeit",
    "3° Top Song": "Rotkäppchen",
    "4° Top Song": "Das Ede aller Lügen",
    "5° Top Song": "Zeichen",
    "Spotify Listeners": "31819",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "107", 
    "Band Name" : "Véhémence",
    "Genre" : "Epic/Melodic Black Metal", 
    "Year Formed": "",
    "Founded In": "Paris, FR",
    "Country": "France",
    "N° of Albums": "3",
    "N° of Singles": "0",
    "Newest Album": "Ordalies",
    "Year": "2022",
    "N°1 Most Popular Album": "Assiégé",
    "2° Most Popular Album": "Par le sang versé",
    "3° Most Popular Album": "Ordalies",
    "Top Song": "De feu et dacier",
    "2° Top Song": "Notre royaume... en cendres",
    "3° Top Song": "Epopée",
    "4° Top Song": "Au blason brûlé",
    "5° Top Song": "La danse des pluies",
    "Spotify Listeners": "5833",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "108", 
    "Band Name" : "Waldgeflüster",
    "Genre" : "Black Metal", 
    "Year Formed": "2005",
    "Founded In": "Munich, DE",
    "Country": "Germany",
    "N° of Albums": "10",
    "N° of Singles": "2",
    "Newest Album": "Dahoam",
    "Year": "2021",
    "N°1 Most Popular Album": "Femundsmarka - Eine Reise in drei Kapiteln",
    "2° Most Popular Album": "Meine Fesseln",
    "3° Most Popular Album": "Mondscheinsonaten	",
    "Top Song": "Graustufen Novembertage",
    "2° Top Song": "Ruinenfelder",
    "3° Top Song": "Die Ruine als Schmuck",
    "4° Top Song": "Klage V - Herbststürme",
    "5° Top Song": "Rotgoldene Novemberwälder",
    "Spotify Listeners": "4883",
    "In tour?": "Yes",
    "When?": "2022/2023",
    "Where?": "EU"},

    {"ID": "109", 
    "Band Name" : "Wardruna",
    "Genre" : "Folk/Euro Ethnic", 
    "Year Formed": "2003",
    "Founded In": "Bergen, NO",
    "Country": "Norway",
    "N° of Albums": "5",
    "N° of Singles": "3",
    "Newest Album": "Kvitravn",
    "Year": "2021",
    "N°1 Most Popular Album": "Runaljod - Yggdrasil",
    "2° Most Popular Album": "Runaljod - gap var Ginnunga",
    "3° Most Popular Album": "Runaljod - Ragnarok",
    "Top Song": "Helvegen",
    "2° Top Song": "Fehu",
    "3° Top Song": "Lyfjaberg",
    "4° Top Song": "Solringen",
    "5° Top Song": "Rotlaust Tre Fell",
    "Spotify Listeners": "547033",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "US"},

    {"ID": "110", 
    "Band Name" : "Warkings",
    "Genre" : "Power Metal", 
    "Year Formed": "2018",
    "Founded In": ", DE",
    "Country": "Germany/Austria/Switzerland",
    "N° of Albums": "4",
    "N° of Singles": "3",
    "Newest Album": "Morgana",
    "Year": "2022",
    "N°1 Most Popular Album": "Reborn",
    "2° Most Popular Album": "Revenge",
    "3° Most Popular Album": "Revolution",
    "Top Song": "Hephaistos",
    "2° Top Song": "The Last Battle",
    "3° Top Song": "Monsters",
    "4° Top Song": "Maximus",
    "5° Top Song": "Fight",
    "Spotify Listeners": "137649",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "111", 
    "Band Name" : "Warlock",
    "Genre" : "Heavy Metal", 
    "Year Formed": "1983",
    "Founded In": "Düsseldorf, DE",
    "Country": "Germany",
    "N° of Albums": "4",
    "N° of Singles": "4",
    "Newest Album": "Triumph and Agony",
    "Year": "1987",
    "N°1 Most Popular Album": "Hellbound",
    "2° Most Popular Album": "Burning the Withces",
    "3° Most Popular Album": "True as Steel",
    "Top Song": "All We Are",
    "2° Top Song": "I Rule The Ruins",
    "3° Top Song": "Fight For Rock",
    "4° Top Song": "True As Steel",
    "5° Top Song": "Kiss Of Death",
    "Spotify Listeners": "460805",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "112", 
    "Band Name" : "Waylander",
    "Genre" : "Celtic Folk Metal", 
    "Year Formed": "1993",
    "Founded In": "Armagh, UK",
    "Country": "United Kingdom",
    "N° of Albums": "5",
    "N° of Singles": "0",
    "Newest Album": "Ériú's Wheel",
    "Year": "2019",
    "N°1 Most Popular Album": "Honour Amongst Chaos",
    "2° Most Popular Album": "Reawakening Pride Once Lost",
    "3° Most Popular Album": "Ériú's Wheel",
    "Top Song": "Born to the Fight",
    "2° Top Song": "Sunrise",
    "3° Top Song": "Walk with honour",
    "4° Top Song": "King of the Faires",
    "5° Top Song": "As the Sun Stands Still",
    "Spotify Listeners": "12019",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "113", 
    "Band Name" : "Wilderun",
    "Genre" : "Symphonic Progressive/Folk Metal", 
    "Year Formed": "2008",
    "Founded In": "Boston, US",
    "Country": "United States",
    "N° of Albums": "4",
    "N° of Singles": "0",
    "Newest Album": "Epigone",
    "Year": "2022",
    "N°1 Most Popular Album": "Veil of Imagination",
    "2° Most Popular Album": "Epigone",
    "3° Most Popular Album": "Olden Tales & Deathly Trails",
    "Top Song": "Passanger",
    "2° Top Song": "Far from Where Dreams Unfurl",
    "3° Top Song": "Exhaler",
    "4° Top Song": "The Unimaginable Zero Summer",
    "5° Top Song": "Woolgatherer",
    "Spotify Listeners": "16485",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "114", 
    "Band Name" : "Wintersun",
    "Genre" : "Symphonic Melodic Death Metal", 
    "Year Formed": "2003",
    "Founded In": "Helsinki, FI",
    "Country": "Finland",
    "N° of Albums": "3",
    "N° of Singles": "0",
    "Newest Album": "The Forest Seasons",
    "Year": "2017",
    "N°1 Most Popular Album": "Wintersun",
    "2° Most Popular Album": "Time I",
    "3° Most Popular Album": "The Forest Seasons",
    "Top Song": "Beyond the Dark Sun",
    "2° Top Song": "Death and the Healing",
    "3° Top Song": "Sons of Winter and Stards",
    "4° Top Song": "Darkness and Frost",
    "5° Top Song": "Land of Snow and Sorrow",
    "Spotify Listeners": "220141",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "115", 
    "Band Name" : "Winterstorm",
    "Genre" : "Power/Folk Metal", 
    "Year Formed": "2008",
    "Founded In": "Bayreuth, DE",
    "Country": "Germnay",
    "N° of Albums": "4",
    "N° of Singles": "0",
    "Newest Album": "Cube of Infinity",
    "Year": "2016",
    "N°1 Most Popular Album": "Kings Will Fall",
    "2° Most Popular Album": "A Coming Storm",
    "3° Most Popular Album": "Cathyron",
    "Top Song": "Kings Will Fall",
    "2° Top Song": "Through the Storm",
    "3° Top Song": "Return to Glory",
    "4° Top Song": "Pacts of Blood and Might",
    "5° Top Song": "In Time We Trust",
    "Spotify Listeners": "15331",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "116", 
    "Band Name" : "Wisdom",
    "Genre" : "Power Metal", 
    "Year Formed": "2001",
    "Founded In": "Budapest, HU",
    "Country": "Hungary",
    "N° of Albums": "4",
    "N° of Singles": "0",
    "Newest Album": "Rise of the Wise",
    "Year": "2016",
    "N°1 Most Popular Album": "Marching for Luberty",
    "2° Most Popular Album": "Rise of the Wise",
    "3° Most Popular Album": "Words of Wisdom",
    "Top Song": "Ravens Night",
    "2° Top Song": "Heaven and Hell",
    "3° Top Song": "Take Me to Neverland",
    "4° Top Song": "War of Angels",
    "5° Top Song": "Rise of the Wise",
    "Spotify Listeners": "28285",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "117", 
    "Band Name" : "Wizard",
    "Genre" : "Epic Power Metal", 
    "Year Formed": "1989",
    "Founded In": "Bocholt, DE",
    "Country": "Germany",
    "N° of Albums": "12",
    "N° of Singles": "0",
    "Newest Album": "Metal in My Head",
    "Year": "2121",
    "N°1 Most Popular Album": "Thor",
    "2° Most Popular Album": "	...of Wariwulfs and Bluotvarwes",
    "3° Most Popular Album": "Odin",
    "Top Song": "Midgards Guardian",
    "2° Top Song": "Metal in My Head",
    "3° Top Song": "I Bring Lught Into the Dark",
    "4° Top Song": "Liar and Betrayer",
    "5° Top Song": "Metal Feast",
    "Spotify Listeners": "15840",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "118", 
    "Band Name" : "Wolfchant",
    "Genre" : "Pagan/Folk Metal", 
    "Year Formed": "2003",
    "Founded In": "Sankt Oswald-Reidlhütte, DE",
    "Country": "Germany",
    "N° of Albums": "7",
    "N° of Singles": "0",
    "Newest Album": "Omega: Bestia",
    "Year": "2021",
    "N°1 Most Popular Album": "Bloodwinter",
    "2° Most Popular Album": "A Pagan Storm",
    "3° Most Popular Album": "Embraced by Fire",
    "Top Song": "Never to Drunk",
    "2° Top Song": "Das Bollwerk",
    "3° Top Song": "A Pagan Storm",
    "4° Top Song": "Bloodwinter",
    "5° Top Song": "Ermit",
    "Spotify Listeners": "22649",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "119", 
    "Band Name" : "Wolfheart",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "2013",
    "Founded In": "Lahti, FI",
    "Country": "Finland",
    "N° of Albums": "6",
    "N° of Singles": "3",
    "Newest Album": "King of the North",
    "Year": "2022",
    "N°1 Most Popular Album": "Shadow World",
    "2° Most Popular Album": "Winterborn",
    "3° Most Popular Album": "Tyhjyys",
    "Top Song": "The King",
    "2° Top Song": "The Hunt",
    "3° Top Song": "Ancestor",
    "4° Top Song": "Shores Of The Lake Simpele",
    "5° Top Song": "The Flood",
    "Spotify Listeners": "68001",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"},

    {"ID": "120", 
    "Band Name" : "Wulfgar",
    "Genre" : "Melodic Death Metal", 
    "Year Formed": "2005",
    "Founded In": "Kristianstad, FI",
    "Country": "Finland",
    "N° of Albums": "3",
    "N° of Singles": "2",
    "Newest Album": "From the Ashes",
    "Year": "2021",
    "N°1 Most Popular Album": "Midgarian Metal",
    "2° Most Popular Album": "With Gods and Legends Unite",
    "3° Most Popular Album": "From the Ashes",
    "Top Song": "Circle of Runes",
    "2° Top Song": "On a Battlefield in Midgard I Will Die",
    "3° Top Song": "Norsemen of Steel",
    "4° Top Song": "From the Ashes",
    "5° Top Song": "Cleansed by Fire",
    "Spotify Listeners": "3251",
    "In tour?": "No",
    "When?": "",
    "Where?": ""},

    {"ID": "122", 
    "Band Name" : "Freedom Call",
    "Genre" : "Power Metal", 
    "Year Formed": "1998",
    "Founded In": "Nuremberg, DE",
    "Country": "Germany",
    "N° of Albums": "10",
    "N° of Singles": "8",
    "Newest Album": "M.E.T.A.L",
    "Year": "2019",
    "N°1 Most Popular Album": "Master of Lught",
    "2° Most Popular Album": "Legend of the Shadowking",
    "3° Most Popular Album": "Land of the Crimson Dawn",
    "Top Song": "Metal Is for Everyone",
    "2° Top Song": "Warriors",
    "3° Top Song": "Hammer of the Gods",
    "4° Top Song": "Land of Light",
    "5° Top Song": "Freedom Call",
    "Spotify Listeners": "165114",
    "In tour?": "Yes",
    "When?": "2022",
    "Where?": "EU"}
    ]

